module: BridgeApp
output: ../Documentation
xcodebuild_arguments:
- -project
- ./BridgeApp/BridgeApp.xcodeproj
- -scheme
- "BridgeApp (iOS)"

author: "Sage Bionetworks"
author_url: https://developer.sagebridge.org
github_url: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK
copyright: "&copy; 2017-2018 [Sage Bionetworks](https://developer.sagebridge.org). All rights reserved."
readme: README.md
min_acl: public
clean: true
skip_undocumented: true
hide_documentation_coverage: true
